version: '3'

services:
  eksler:
    build:
      context: .
      x-bake:
        tags:
          - ghcr.io/${GITHUB_REPOSITORY}:latest
          - ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA}
        platforms:
          - linux/amd64
          - linux/arm64
    entrypoint:
      - "/app/entrypoint.sh"
    volumes:
      - .:/app
      - ./.bash_history:/root/.bash_history
      - $HOME/.kube:/root/.kube
    env_file:
      - .env
