# https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/values.yaml
awsRegion: ${REGION}

autoDiscovery:
  clusterName: ${CLUSTER_NAME}

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
                - "aws-cluster-autoscaler"
        topologyKey: "kubernetes.io/hostname"

extraArgs:
  expander: most-pods
  max-node-provision-time: 5m
  scale-down-delay-after-add: 10m
  scale-down-unneeded-time: 10m

resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 1
    memory: 512Mi

image:
  repository: k8s.gcr.io/autoscaling/cluster-autoscaler
  tag: v1.21.1
  pullPolicy: IfNotPresent

nodeSelector:
  autoscaler: "yes"

tolerations:
  - key: node.kubernetes.io/not-ready
    operator: Exists
    effect: NoExecute
    tolerationSeconds: 10
  - key: node.kubernetes.io/unreachable
    operator: Exists
    effect: NoExecute
    tolerationSeconds: 10

# podDisruptionBudget:
#   maxUnavailable: 1

#TODO:
replicaCount: 1
