# https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
alertmanager:
  enabled: false

pushgateway:
  enabled: false

configmapReload:
  prometheus:
    enabled: false

kubeStateMetrics:
  enabled: false

server:
  global:
    scrape_interval: 15s
    scrape_timeout: 10s

  nodeSelector:
    prometheus: "yes"
  persistentVolume:
    enabled: false
  emptyDir:
    sizeLimit: 4Gi
  terminationGracePeriodSeconds: 10
  resources:
    limits:
      cpu: 2
      memory: 5Gi
    requests:
      cpu: 2
      memory: 5Gi

  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 10
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 10

nodeExporter:
  resources:
    limits:
      cpu: 0.25
      memory: 512Mi
    requests:
      cpu: 0.25
      memory: 512Mi
